### ISSUE TITLE
Broken Markdown Link 

### ISSUE THREAD

**Issue by kylekirkby** [OP-TEE/optee_docs#10]
Hi @jbech-linaro,

There's a broken link in an OP-TEE post to https://github.com/OP-TEE/optee_os/blob/master/documentation/secure_storage_rpmb.md

But noticed in the new docs that it's referenced here but doesn't link to anywhere.

https://github.com/OP-TEE/optee_docs/blame/master/architecture/secure_storage.rst#L25

Regards,

Kyle

**Comment by jbech-linaro** [comment]
Good catch, I'll update and close this ticket once done.

**Comment by jbech-linaro** [comment]
https://github.com/OP-TEE/optee_docs/pull/40 fixed this, closing this ticket. Thanks everyone!
