### ISSUE TITLE
How to use any kernel git tree?

### ISSUE THREAD

**Issue by jarkk0sakkinen** [OP-TEE/optee_docs#100]
Is there a parameter to point the op-tee build to an arbitrary kernel git?

**Comment by jbech-linaro** [comment]
Hi @jarkk0sakkinen , in most cases it should be sufficient to just checkout another tree. Having said that, there are couple of out tree patches in the kernel fork that you get when checking out an OP-TEE project according to the instructions that might be needed in some cases (mainly dts changes for certain hardware and the "secure data path"). So, simply try checking out another tree and rebuild. If you have any issue, we can help you to get it sorted.

**Comment by jarkk0sakkinen** [comment]
Thanks, I think I can manage this :-) I was just hoping there was some handy parameter that I can use say "please use this tree" but I can work my way with the existing thing too. Thank you.
