### ISSUE TITLE
Assuming x86_64 architecture

### ISSUE THREAD

**Issue by mefistotelis** [OP-TEE/optee_docs#112]
Following the instructions:
https://optee.readthedocs.io/en/latest/building/devices/qemu.html

When I run:

```
make toolchains
```

The tool just assumes I'm on 64-bit Linux under x86 arch. Shouldn't there at least be a check to confirm that?

Running on i686 kernel causes a message about bad executable format when `make` tries to execute the tools.
(though target devs for this project should be able to figure out the cause quickly, so this is low priority issue)

**Comment by jforissier** [comment]
Hi @mefistotelis,

I think x86_64 is so overwhelmingly used that it's not really a problem in practice. That being said, adding a check would certainly be a good idea and patches are welcome.

**Comment by jbech-linaro** [comment]
Agree with @jforissier , so @mefistotelis do you think you can send a patch for it so we can close this issue?

**Comment by mefistotelis** [comment]
Yes, can do.
