### ISSUE TITLE
Broken link in Porting Guidelines

### ISSUE THREAD

**Issue by goxul** [OP-TEE/optee_docs#142]
In the section conf.mk, the document refers to "... Please see Platform-specific configuration and flags in the build system documentation.", 

where the link is: https://optee.readthedocs.io/en/latest/architecture/build_system.md#platform-specific-configuration-and-flags.

The link, however, seems to be broken - what would be the correct link for the relevant section?

**Comment by jbech-linaro** [comment]
Hi @goxul 

This is the correct link: https://optee.readthedocs.io/en/latest/building/gits/optee_os.html#build-system (scroll down to `platform_config.h` to get the exact location.

I'll send an update to the docs. Thanks for reporting the issue.
