### ISSUE TITLE
Invalid header reference in "Extensions" section

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_docs#143]
https://optee.readthedocs.io/en/latest/architecture/globalplatform_api.html#tee-internal-core-api says Trusted Applications should include header file `tee_api_defines_extensions.h` to import the definitions of the extensions.

Shouldn't it be `tee_internal_api_extensions.h`?

**Comment by jforissier** [comment]
Hi @Hussain1811,

You are right, `tee_internal_api_extensions.h` is the main header file for extensions and TAs should generally include that file if they need to use any extension.
Note however that in some cases like key derivation extensions, no new function is defined and it is enough to include `tee_api_defines_extensions.h` to get the new macros. But including `tee_internal_api_extensions.h` will work too.

I will create a PR to fix the doc. Thanks for reporting.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_docs/pull/144

**Comment by Hussain1811** [comment]
Thank you

**Comment by jbech-linaro** [comment]
Thanks @Hussain1811 and @jforissier for reporting and fixing, I've just merged #144, so I'm closing this issue.
