### ISSUE TITLE
Secure element integration

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_docs#154]
should I provide some entry about the SE050  integration in OP-TEE or is it not necessary?

**Comment by jbech-linaro** [comment]
Never hurts in my opinion to add something in the docs that clarifies a) what it is about and what problem it solves b) how to enable it c) how to use it. So if you have time and are willing to do so, please by all means go a head.

**Comment by ldts** [comment]
great. thanks @jbech-linaro
