### ISSUE TITLE
Mistake in the core docs

### ISSUE THREAD

**Issue by jewcomm** [OP-TEE/optee_docs#183]
In section Notifications, the documents https://github.com/OP-TEE/optee_docs/blob/master/architecture/core.rst mistake in "..driver need a bootom half..". May be should be bottom?

**Comment by jenswi-linaro** [comment]
You're right @jewcomm, feel free to make a pull request to fix it.

**Comment by jewcomm** [comment]
Create [pull request](https://github.com/OP-TEE/optee_docs/pull/184) .
Close issue.
