### ISSUE TITLE
Outdated platform support list

### ISSUE THREAD

**Issue by b49020** [OP-TEE/optee_docs#33]
It looks like https://optee.readthedocs.io/general/platforms.html hasn't been updated with latest platform support added in OP-TEE like i.MX8MQ/MM etc.

Shouldn't we ask platform authors to update this file also whenever a new platform support is added in OP-TEE? As it looks like a common location for people to search if a particular platform is supported in OP-TEE.

-Sumit

**Comment by jbech-linaro** [comment]
Yes, we always need to have this and other documentation in the back of our heads when reviewing other patches. But, if you know what is missing, please just add it. It doesn't have to come from the maintainers directly.

**Comment by b49020** [comment]
Yeah, I could add but looking at fields in the platform table like "Publicly available?", "Maintained?" and a public link, it seems that those could be appropriately provided by platform maintainer only.

BTW, I guess for i.MX8MQ/MM I could find corresponding info in commit: https://github.com/OP-TEE/optee_os/commit/42615b81f3f7b3bebd6a8e2b5e325ac477bc4e4b. So will create a patch for that.

**Comment by jbech-linaro** [comment]
> it seems that those could be appropriately provided by platform maintainer only

True! In those cases, please add them if you know their GitHub alias, use that, if not you can try the alias for the whole platform (https://github.com/orgs/OP-TEE/teams/maintainers/teams) and all maintainers for that will get a notification. For example @OP-TEE/plat-imx.

**Comment by jforissier** [comment]
Speaking of teams... how about this: https://github.com/OP-TEE/optee_os/pull/3229?
