### ISSUE TITLE
Using url for internal links

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_docs#37]
Is it possible to use the full url rather than `` :ref:`page_name` `` for internal links as well in a page, specifically for `aosp.rst`, like [this](https://github.com/vchong/optee_docs/commit/a6bfcc2ebf12f9b32fb17c48098e3fe6cb12bac5)? This is to enhance portability, i.e. be able to use the page (`.rst` doc) as-is at a different location, e.g. `github.com`, etc.

A specific use case is when making an aosp release. The main release page (e.g. [here](https://github.com/linaro-swg/optee_android_manifest/tree/3.6.1)) has a copy of `aosp.rst` (renamed as `readme.rst`) to capture the build instructions at the time. We don't/can't just point/link directly to `aosp.rst` itself since it's a moving target, i.e. updated to always reflects the current/latest build instructions.

If we use the page as-is right now, it would show up like [here](https://github.com/linaro-swg/optee_android_manifest/tree/3646478efa2fb66c75bf82ef47fa45929ebfa5c0), i.e. the internal links using `` :ref:`page_name` `` show up literally and don't work.

**Comment by jbech-linaro** [comment]
> Is it possible to use the full url rather than `` :ref:`page_name` `` for internal links as well in a page, specifically for `aosp.rst`, like [this](https://github.com/vchong/optee_docs/commit/a6bfcc2ebf12f9b32fb17c48098e3fe6cb12bac5)?

Yes, but I don't like it TBH. I think the solution to this issue is to
1. remove the content on the "main release page" and simply add a redirection there to https://optee.readthedocs.io (/.../aosp.rst)
2. Keep all release notes, build instructions at optee.readthedocs.io

> We don't/can't just point/link directly to aosp.rst itself since it's a moving target, i.e. updated to > always reflects the current/latest build instructions.

Why? What is moving? You mean that old instructions will be replaced and overwritten. I.e., old instructions gets lost? I see two solutions to that. Tag optee_docs just as we're tagging the other gits and/or add a second aosp-old.rst page that contains legacy instructions (I'd prefer just tags).

**Comment by vchong** [comment]
> I see two solutions to that. Tag optee_docs just as we're tagging the other gits and/or add a second aosp-old.rst page that contains legacy instructions (I'd prefer just tags).

In that case, can you please tag `20441fe7928c30a5f5ffb4c6b22ef5262a15c42b` as `aosp-3.6.1` please? Thanks!

**Comment by jbech-linaro** [comment]
Done! https://github.com/OP-TEE/optee_docs/releases/tag/aosp-3.6.1

**Comment by jbech-linaro** [comment]
And I've enabled it in readthedocs also, so now this (https://optee.readthedocs.io/en/aosp-3.6.1/) will last "forever"

**Comment by jforissier** [comment]
> And I've enabled it in readthedocs also, so now this (https://optee.readthedocs.io/en/aosp-3.6.1/) will last "forever"

:+1+ will you create a tag for each new OP-TEE release?

**Comment by jbech-linaro** [comment]
> :+1+ will you create a tag for each new OP-TEE release?

Yes and I've also been thinking about adding optee_docs to our manifests, since I believe that would make tagging etc easier when doing releases.

**Comment by jforissier** [comment]
>> :+1+ will you create a tag for each new OP-TEE release?

> Yes and I've also been thinking about adding optee_docs to our manifests, since I believe that would make tagging etc easier when doing releases.

Good idea IMO.

**Comment by vchong** [comment]
Thanks! Closing.
