### ISSUE TITLE
Is there any plan for supporting Raspberry 4?

### ISSUE THREAD

**Issue by scotthuang1989** [OP-TEE/optee_docs#73]
As Raspberry 4 have released for a while, does op-tee have any plan to support it?

**Comment by jforissier** [comment]
Hi @scotthuang1989 ,

I don't think so, but if someone volunteers to provide patches and maintain the platform it can certainly change.

**Comment by scotthuang1989** [comment]
got it, I guess I will buy a Raspberry 3B+.  we want build some demo apps on it,  a stable release is very important.
