### ISSUE TITLE
Support for platform specific documentation

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_docs#85]
Hi,

I'd like to document the current state of the `imx` platform within OP-TEE, but I don't know where it fits into the current documentation structure:
- It could be placed under architecture, under a new subheading
- We could add a new platform specific Heading.
- Platform Support under getting started probably doesn't fit.

**Comment by jbech-linaro** [comment]
Architecture typically contains generic information and device specifics have been placed under https://optee.readthedocs.io/en/latest/building/devices/index.html

So, for now I would suggest to put the IMX specifics there under a a new page. I.e., `/building/devices/imx.rst`.

**Comment by Emantor** [comment]
Thanks, I couldn't find it during my initial search.
