### ISSUE TITLE
[Query] : Documenting new board

### ISSUE THREAD

**Issue by prabhakarlad** [OP-TEE/optee_docs#91]
Hi 

In platforms.rst file what does "Publicly available" mean here. What is the criteria for the board to be marked as YES/NO.

Cheers,
Prabhakar

**Comment by jbech-linaro** [comment]
Hi,

If any person on the planet can buy the board from some supplier, then it's publicly available. If it's a board that has official support but can only be shared withing a certain group of people and/or companies, then it's not a publicly available board. I hope that clarifies it.

**Comment by prabhakarlad** [comment]
Thanks that clarifies my doubt.
