### ISSUE TITLE
proposal to move AOSP in the build article layout

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_docs#99]
Could we change the ordering in build & doc article?
It currently goes this way:
___
**Build and run**

_(some text)_

* AOSP
  * Prerequisites
  * Build instructions
  * Flashing the image
  * Partial flashing
  * Experimental prebuilts
  * Running xtest
  * Running VTS Gtest unit for Gatekeeper and Keymaster (Optional)
  * Enable adb over USB
  * Known issues
* Device specific information
  * DeveloperBox
  * FVP
  * HiKey 620
  * ...
___

And one hardly goes first clearing to the generic entry point: device ways and the prerequisites/toolchain parts.

I suggest we change to:
___
**Build and run**

_(still the same text...)_

* Prerequisites
* Toolchains
  * Download/install
  * Export PATH
  * LLVM / Clang
* Device specific information
  * DeveloperBox
  * FVP
  * HiKey 620
  * ...
* **AOSP**
  * **Prerequisites**
  * **Build instructions**
  * **Flashing the image**
  * **...**
* Linux kernel TEE framework
* OP-TEE gits
  * ...
* Trusted Applications
  * ...
___

What do you think about it?

**Comment by vchong** [comment]
Agree that the change does make the ordering look more sequential, but the AOSP tab seems to get in the way of all the other 'Linux' tabs, so how do you all feel about moving the AOSP tab one level up and renaming it to 'Build and run - AOSP'? If so, we should maybe also consider renaming the 'Build and run' tab to 'Build and run - Linux'.

**Comment by jbech-linaro** [comment]
The reason for having it as it is (sorted alphabetically) is that it should be easy to find the sections when they grow. I think I prefer keeping it like that. However, the could make the "landing page" for Build and run a bit more informative. Jerome made it a bit better a while ago. But we could add more to it. We could for example move everything here "https://optee.readthedocs.io/en/latest/building/gits/build.html"  to the "landing page".

**Comment by etienne-lms** [comment]
Or moving prerequisite and tooclhain subsections  in a new section "About building the images", which would go first...

**Comment by etienne-lms** [comment]
and renamint "Device specific ..." to "And now the device specific ..." :)

**Comment by jbech-linaro** [comment]
In short what you are saying (and I tend to agree) is that a) there is no natural order for the instructions and b) it's somewhat tricky to find the information that is of interest (how to actually build ...). Send a PR and we can continue to discuss. Alphabetic sorting is not a hard rule, but the more items you have in the menu-bar, the more I'll start to ask for it. If there is just a handful of items, then I'm OK with making necessary changes to make the page more natural to read. When updating, please have look at this page first, since there are some tips and guidance -> https://optee.readthedocs.io/en/latest/building/gits/optee_docs.html

**Comment by jforissier** [comment]
> Alphabetic sorting is not a hard rule, but the more items you have in the menu-bar, the more I'll start to ask for it. I

Not sure I agree with that, in fact I think we'd better use some kind of logical order whenever possible, as if writing a book, introduce first things first... then alphabetically is OK when there is no logical order that stands out. As for searching I very often use the search box anyways, I don't look at the TOC much in this case.

But I have no strong opinion, readthedocs is pretty good and convenient.

**Comment by etienne-lms** [comment]
I've created https://github.com/OP-TEE/optee_docs/pull/104. I really think it's worth it.

**Comment by jbech-linaro** [comment]
#104 has been merged, thanks Etienne!
